/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-05 11:40:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");

    	String userid = (String)session.getAttribute("userid");
    	String usertype = (String)session.getAttribute("usertype");
    
      out.write("\n");
      out.write("    \n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<title>WatchDogs</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"http://dmshop.kr/theme/moon/css/default_shop.css?ver=12928\">\n");
      out.write("<link rel=\"stylesheet\" href=\"http://dmshop.kr/theme/moon/skin/shop/basic/style.css?ver=12928\">\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// 자바스크립트에서 사용하는 전역변수 선언\n");
      out.write("var g5_url       = \"http://dmshop.kr\";\n");
      out.write("var g5_bbs_url   = \"http://dmshop.kr/bbs\";\n");
      out.write("var g5_is_member = \"\";\n");
      out.write("var g5_is_admin  = \"\";\n");
      out.write("var g5_is_mobile = \"\";\n");
      out.write("var g5_bo_table  = \"\";\n");
      out.write("var g5_sca       = \"\";\n");
      out.write("var g5_editor    = \"\";\n");
      out.write("var g5_cookie_domain = \"\";\n");
      out.write("var g5_shop_url = \"http://dmshop.kr/shop\";\n");
      out.write("var g5_theme_shop_url = \"http://dmshop.kr/theme/moon/shop\";\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/js/bootstrap.js\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/js/jquery.shop.menu.js?ver=1631\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/js/common.js?ver=1631\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/js/icecream.js?ver=1631\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/js/wrest.js?ver=1631\"></script>\n");
      out.write("<script src=\"http://dmshop.kr/theme/moon/js/jquery.flexslider-min.js\"></script>\n");
      out.write("<link href=\"http://dmshop.kr/theme/moon/js/flexslider.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"hello_wrap\">\n");
      out.write("\n");
      out.write("<!-- 상단 시작 { -->\n");
      out.write("<div id=\"hd\">\n");
      out.write("\n");
      out.write("    <div id=\"tnb\">\n");
      out.write("        <h3>메뉴</h3>\n");
      out.write("        <ul>    \n");
      out.write("\n");
      out.write("            <li><a href=\"signup.wd\"><b>회원가입</b></a></li>\n");
      out.write("            <!-- <li class=\"tnb_cart\"><a href=\"http://dmshop.kr/shop/cart.php\"><i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i> 참고용 장바구니?</a></li> -->\n");
      out.write("            <li class=\"tnb_bookmark\"><a href=\"home.jsp\" ><i class=\"fas fa-home\"></i> HOME<span class=\"st_bg\"></span></a></li>\n");
      out.write("		</ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("      \n");
      out.write("    <div id=\"hd_wrapper\">\n");
      out.write("        \n");
      out.write("        <div id=\"logo\"><a href=\"home.jsp\"><img src=\"resources/logo.png\" width=\"150px\" height=\"100px\" alt=\"WatchDogs\"></a></div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("        <nav class=\"nav\">\n");
      out.write("        <div id=\"gnb\" >\n");
      out.write("            <h2>사이트 카테고리</h2>\n");
      out.write("            <ul id=\"gnb_1dul\">\n");
      out.write("         \n");
      out.write("			<li class=\"gnb_1dli\" style=\"z-index:999\">\n");
      out.write("			    <a href=\"introduction.wd\" class=\"gnb_1da gnb_1dam\">소개</a>\n");
      out.write("			    <div class=\"gnb_2dul gnb_2dli\" style=\"z-index:999\"><div class=\"gnb_2dul_left\"><strong class=\"gnb_2ul_tit\">소개</strong>      \n");
      out.write("			  </div></div></li>\n");
      out.write("			  \n");
      out.write("			<li class=\"gnb_1dli\" style=\"z-index:998\">\n");
      out.write("			    <a href=\"adoptpage.wd\" class=\"gnb_1da gnb_1dam\">입양</a>\n");
      out.write("			    <div class=\"gnb_2dul gnb_2dli\" style=\"z-index:998\"><div class=\"gnb_2dul_left\"><strong class=\"gnb_2ul_tit\">입양</strong><ul>      \n");
      out.write("			            <li><a href=\"adoptproceeding.wd\" class=\"gnb_2da\">입양 진행 중</a></li>\n");
      out.write("			            <li><a href=\"adopt.wd\" class=\"gnb_2da\">입양 대기 중</a></li>\n");
      out.write("			            <li><a href=\"adoptcomplete.wd\" class=\"gnb_2da\">입양 완료</a></li>\n");
      out.write("			            <li><a href=\"adopttraining.wd\" class=\"gnb_2da\">훈련중</a></li>\n");
      out.write("			    </ul></div></div></li>\n");
      out.write("			    \n");
      out.write("			<li class=\"gnb_1dli\" style=\"z-index:997\">\n");
      out.write("			    <a href=\"trainerlist.wd\" class=\"gnb_1da gnb_1dam\">훈련사 소개</a>\n");
      out.write("			    <div class=\"gnb_2dul gnb_2dli\" style=\"z-index:997\"><div class=\"gnb_2dul_left\"><strong class=\"gnb_2ul_tit\">훈련사 소개</strong>        \n");
      out.write("			    </div></div></li>\n");
      out.write("			    \n");
      out.write("			<li class=\"gnb_1dli\" style=\"z-index:996\">\n");
      out.write("			    <a href=\"notice.wd\" class=\"gnb_1da gnb_1dam\">게시판</a>\n");
      out.write("			    <div class=\"gnb_2dul gnb_2dli\" style=\"z-index:996\"><div class=\"gnb_2dul_left\"><strong class=\"gnb_2ul_tit\">게시판</strong><ul>        \n");
      out.write("			            <li><a href=\"noticelist.wd\" class=\"gnb_2da\">공지</a></li>\n");
      out.write("			            <li><a href=\"reviewlist.wd\" class=\"gnb_2da\">후기</a></li>\n");
      out.write("			    </ul></div></div></li>\n");
      out.write("			<li class=\"gnb_1dli\" style=\"z-index:995\">\n");
      out.write("			    <a href=\"longintypecheck.wd\" class=\"gnb_1da gnb_1dam\">마이 페이지</a>\n");
      out.write("			    <div class=\"gnb_2dul gnb_2dli\" style=\"z-index:995\"><div class=\"gnb_2dul_left\"><strong class=\"gnb_2ul_tit\">마이 페이지</strong>      \n");
      out.write("			</div></div></li>\n");
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    	</nav>\n");
      out.write("            \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("	\n");
      out.write("        	\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<style>\n");
      out.write("		#must_read{background-color: #fc6; border-color: #ebccd1; text-align: center }\n");
      out.write("		#must_read h3{color: #a94442; font-weight: 400; padding: 20px 0; }\n");
      out.write("		\n");
      out.write("		.top_banner{width:1050px; margin:0 auto; margin-top:50px}\n");
      out.write("		.top_banner td{}\n");
      out.write("	</style>\n");
      out.write("	\n");
      out.write("	<section id=\"must_read\">\n");
      out.write("	    <h3> </h3>\n");
      out.write("	</section>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.touchSlider.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("//<![CDATA[\n");
      out.write("$(document).ready(function() {\n");
      out.write("	$(\"#mb_slide\").touchSlider({\n");
      out.write("		view : 1,\n");
      out.write("		autoplay : {\n");
      out.write("			enable : true,\n");
      out.write("			pauseHover : true,\n");
      out.write("			interval : 8000,\n");
      out.write("		},\n");
      out.write("		btn_prev : $(\"#mb_slide\").next().find(\".btn_prev\"),\n");
      out.write("		btn_next : $(\"#mb_slide\").next().find(\".btn_next\"),\n");
      out.write("	});\n");
      out.write("});\n");
      out.write("//]]>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    $(window).scroll(function(){\n");
      out.write("      var sticky = $('.nav'),\n");
      out.write("          scroll = $(window).scrollTop();\n");
      out.write("\n");
      out.write("      if (scroll >= 200) sticky.addClass('fixed');\n");
      out.write("      else sticky.removeClass('fixed');\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(function (){\n");
      out.write("        var $category = $(\"#category\");\n");
      out.write("\n");
      out.write("        $(\"#menu_open\").on(\"click\", function() {\n");
      out.write("            $category.css(\"display\",\"block\");\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#category .close_btn\").on(\"click\", function(){\n");
      out.write("            $category.css(\"display\",\"none\");\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("   		\n");
      out.write("   		<div class=\"banner\">\n");
      out.write("   			<img src=\"resources/banner.png\" width=\"100%\" height=\"400px\" alt=\"banner\" align=\"middle\">\n");
      out.write("   		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents\">\n");
      out.write("			\"개는 자기 자신보다 당신을 더 사랑하는<p>\n");
      out.write("			이 세상의 유일한 생명체이다.\"\n");
      out.write("		</div>	\n");
      out.write("		\n");
      out.write("		<div class=\"contents2\">\n");
      out.write("			- Josh Billings\n");
      out.write("		</div>	\n");
      out.write("		\n");
      out.write("		<div class=\"blank\"></div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents3\">\n");
      out.write("			혹시, <br><br>\n");
      out.write("			길가의 강아지<br><br>\n");
      out.write("			그냥 지나친 적 없으신가요?\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents4\">\n");
      out.write("   			<img src=\"resources/newsis.jpg\" width=\"250px\" height=\"400px\" alt=\"유기동물 현황_1\" >\n");
      out.write("    		<img src=\"resources/DailyVET.png\" width=\"600px\" height=\"400px\" alt=\"유기동물 현황_2\">\n");
      out.write("   		</div>\n");
      out.write("   		\n");
      out.write("   		<div class=\"contents3\">\n");
      out.write("   			반려동물을 소유물이라고 생각하고 버리거나 학대하는 일이<br><br>\n");
      out.write("   			끊임 없이 벌어지고 있습니다. \n");
      out.write("   		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"blank\"></div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents3\">\n");
      out.write("   			<img src=\"resources/dogicon.png\" width=\"50px\" height=\"50px\" alt=\"dog_icon\" ><br>\n");
      out.write("   			모두의 <b>관심</b>이 필요합니다.<br><br>\n");
      out.write("   			\n");
      out.write("   			반려견들이 더이상 상처를 받지 않고<br>\n");
      out.write("   			<font color=\"#ffad06\">새롭게 시작할 수 있도록</font> <br><br>\n");
      out.write("   			\n");
      out.write("   			<b>저희 <font color=\"#ffad06\">Watch Dogs</font>가 함께 합니다.</b>\n");
      out.write("   		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents5\">\n");
      out.write("			<img src=\"resources/curved_arrow.png\" width=\"30px\" height=\"30px\" alt=\"dog_icon\" > &nbsp; 찾아 오시는 길 <br>\n");
      out.write("		</div>	\n");
      out.write("		\n");
      out.write("		<div class=\"contents5\">\n");
      out.write("			<div id=\"map\" style=\"width:90%;height:350px;\"></div>\n");
      out.write("		</div>\n");
      out.write("		<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=9fc6bb27417d985e141201e29ea4be94&libraries=services\"></script>\n");
      out.write("		<script>\n");
      out.write("			var mapContainer = document.getElementById('map'), // 지도를 표시할 div \n");
      out.write("		    mapOption = { \n");
      out.write("		        center: new kakao.maps.LatLng(37.50216, 127.02529), // 지도의 중심좌표\n");
      out.write("		        level: 3 // 지도의 확대 레벨\n");
      out.write("		    };\n");
      out.write("		\n");
      out.write("			var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\n");
      out.write("		\n");
      out.write("			// 마커가 표시될 위치입니다 \n");
      out.write("			var markerPosition  = new kakao.maps.LatLng(37.50216, 127.02529); \n");
      out.write("		\n");
      out.write("			// 마커를 생성합니다\n");
      out.write("			var marker = new kakao.maps.Marker({\n");
      out.write("			    position: markerPosition\n");
      out.write("			});\n");
      out.write("		\n");
      out.write("			// 마커가 지도 위에 표시되도록 설정합니다\n");
      out.write("			marker.setMap(map);\n");
      out.write("		\n");
      out.write("			// 아래 코드는 지도 위의 마커를 제거하는 코드입니다\n");
      out.write("			// marker.setMap(null);\n");
      out.write("		</script>\n");
      out.write("		\n");
      out.write("		<div class=\"contents5\">\n");
      out.write("			<img src=\"resources/phone.png\" width=\"30px\" height=\"30px\" alt=\"dog_icon\" > &nbsp; 연락처. &nbsp;&nbsp; 010-1234-5678\n");
      out.write("			<br><br>\n");
      out.write("			<img src=\"resources/email.png\" width=\"30px\" height=\"30px\" alt=\"dog_icon\" > &nbsp; 이메일. &nbsp;&nbsp; WatchDogs@gmail.com\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents4\">\n");
      out.write("			<img src=\"resources/logo.png\" width=\"300px\" height=\"200px\" alt=\"dog_icon\" >\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"contents5\">\n");
      out.write("				| 강남 본사 위치 : 서울특별시 서초구 서초4동 강남대로 441 <br><br>\n");
      out.write("				| 대표 : 홍길동 (사업자 등록번호 : 111-22-33333)<br><br>\n");
      out.write("				| 동물판매 등록번호 : 1111111-222-3333-44444\n");
      out.write("		</div>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("    <!-- 중간 내용 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 하단 시작 { -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	#bottom_copy{background-color:#3d3e3e; width:100%; margin-top:100px;}\n");
      out.write("	#bottom_copy .w1200{width: 1200px; margin:0 auto; color:#EDEDED; padding: 10px 42px; box-sizing: border-box; font-size: 0.8em; background-color:#3d3e3e;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"bottom_copy\">\n");
      out.write("	<div class=\"w1200\">\n");
      out.write("	    <p>Copyright © WatchDogs. All Rights Reserved.</p>\n");
      out.write("	    010-1234-5678\n");
      out.write("	    서울특별시 서초구 서초동 1305 서산빌딩 더조은 6조\n");
      out.write("	</div>\n");
      out.write("</section>\n");
      out.write("	\n");
      out.write("    <script>\n");
      out.write("    $(function() {\n");
      out.write("        $(\"#top_btn\").on(\"click\", function() {\n");
      out.write("            $(\"html, body\").animate({scrollTop:0}, '500');\n");
      out.write("            return false;\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"http://dmshop.kr/js/sns.js\"></script>\n");
      out.write("<!-- } 하단 끝 -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
